name: Delete Environment

on:
  push:
    branches: [main, beta, alpha]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.CLEANUP_TOKEN }}
          environment: Production